version: '3'
services:
  postgresql:
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phoenix_study
    ports:
      - '5432:5432'
